
wandb:
  run_name: "upstage/solar-pro" # name of model

api: "openai-compatible"
base_url: "http://solar-pro-vllm-cluster-alb-3-1453891318.us-east-2.elb.amazonaws.com/v1"  # 外部APIのエンドポイント。値はOpenrouterを例としている
batch_size: 32

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "syn-pro" #  "UpstageShareKarakuri/solar-enkoja-31b-64k-2.0.0-chat.3"  # APIで使用するモデル名
  bfcl_model_id: syn-pro-FC # if it doesn't work, find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: "api"# "Small (<10B)", "Medium (10–30B)", "Large (30B+)"
  release_date: 10/15/2025
  base_model: # base model name such as "llama3.1", "qwen2.5"


generator:
  extra_body:
    chat_template_kwargs:
      enable_thinking: false  ### !!!
  max_tokens: 32768 
  temperature: 0.1
  top_p: 1


jaster:
  override_max_tokens: 32768

jbbq:
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

toxicity:
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

jtruthfulqa:
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

swebench:
  max_tokens: 32768
  fc_enabled: false

mtbench:
  generator_config:
    max_tokens: 24576  # 32768
    temperature: 0.3
    top_p: 1
  temperature_override:
    writing: 0.3
    roleplay: 0.3
    extraction: 0.3
    math: 0.3
    coding: 0.3
    reasoning: 0.3
    stem: 0.3
    humanities: 0.3

bfcl:
  temperature: 0.3  ### 使用中のハンドラでは下記ではなくこちらが反映される
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

hallulens:
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

hle:
  generator_config:
    max_tokens: 32768
    temperature: 0.3
    top_p: 1

arc_agi:
  max_output_tokens: 32768